name: QA Deployment

on: 
  workflow_dispatch:
    paths:
      - "force-app/main/default/**"

jobs:
  validate:
    # if: github.event.pull_request.merge == true
    runs-on: ubuntu-latest
    environment: QA
    container:
      image: awareservices/sfdx-cli:latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Authenticate QA Org
        run: |
          echo ${{ secrets.AUTH_URL }} > authURL
          sfdx auth:sfdxurl:store -f authURL -a "QA Org"
      - name: Generate Deployment Package
        run: |
          sfdx force:source:convert -r "force-app" -d "deploy/"
      - name: Validate Deployment
        run: |
          ID=$(sfdx force:source:deploy -p "deploy/" -c -u "QA Org" | sed 's/^ID: \(.*\)/\1/')
          echo $ID
      - name: get properties
        id: json_properties
        uses: zoexx/github-action-json-file-properties@release
        with:
          file_path: result
      - name: log json output
        run: |
          echo ${{ steps.json_properties.outputs }}
      #- name: Deploy Package
        #run: |
          #sfdx force:source:deploy -p "deploy/" --verbose -u "QA Org" -q ${{ steps.json_properties.outputs.result.id }}

