name: QA Deployment

on: workflow_dispatch

jobs:
  validate:
    # if: github.event.pull_request.merge == true
    runs-on: ubuntu-latest
    environment: QA
    container:
      image: awareservices/sfdx-cli:latest
    steps:
      - name: Authenticate QA
        run: |
          echo ${{ secrets.AUTH_URL }} > authURL
          sfdx auth:sfdxurl:store -f qaAuthUrl -a qa
