name: QA Deployment

on: 
  workflow_dispatch:
    paths:
      - "force-app/main/default/**"

jobs:
  validate:
    # if: github.event.pull_request.merge == true
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.step1.outputs.jobId }}
    environment: QA
    container:
      image: awareservices/sfdx-cli:latest
    steps:
      - name: Install JQ Library
        run: |
          sudo apt-get install jq
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Authenticate QA Org
        run: |
          echo ${{ secrets.AUTH_URL }} > authURL
          sfdx auth:sfdxurl:store -f authURL -a "QA Org"
      - name: Generate Deployment Package
        run: |
          sfdx force:source:convert -r "force-app" -d "deploy/"
      - name: Validate Deployment
        run: |
          ID=$(sfdx force:source:deploy --json -p "deploy/" -c --verbose -u "QA Org")
          echo $ID > "deploy/validate/output.json"
          # sfdx force:source:deploy --json -p "deploy/" -c --verbose -u "QA Org" > "deploy/result.json"
          # echo "deploy/result.json"
      - name: Deploy Package
        run: |
          sfdx force:source:deploy -p "deploy/" --verbose -u "QA Org" -q $ID

