# validate on seperate instance
# on success, deploy to validation box AND QA box
# on failure email someone
name: QA Deploy

on: 
  pull_request:
    types: 
      - closed
    paths:
      - "force-app/main/default/**"

jobs:
  validate:
    if: ${{ github.event.pull_request.merged }}
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    environment: QA
    container:
      image: salesforce/salesforcedx:latest-full
    steps:
      - uses: mshick/add-pr-comment@v2
        with:
          message: |
            "QA Package Validation in Progress"
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Authenticate QA Org
        run: |
          echo ${{ secrets.AUTH_URL }} > authURL
          sfdx auth:sfdxurl:store -f authURL -a "QA Org"
      - name: Generate Deployment Package
        run: |
          sfdx force:source:convert -r "force-app" -d "deploy/src/" --json
      - name: Deploy Package
        id: deployment
        run: |
          URL=$(sfdx force:org:display -u "QA Org" --json | jq -r .result.instanceUrl)
          echo "orgUrl=$URL" >> $GITHUB_OUTPUT
          echo "QA Org URL: ${{ steps.deployment.outputs.orgUrl }}"
          #sfdx force:source:deploy --verbose -u "QA Org" -q "${{ steps.validation.outputs.deployId }}"
          sfdx force:source:deploy --verbose -u "QA Org" -p "deploy/src/"

