# validate on seperate instance
# on success, deploy to validation box AND QA box
# on failure email someone
name: QA Validate

on: 
  pull_request:
    types: 
      - opened
    paths:
      - "force-app/main/default/**"

jobs:
  validate:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    environment: QA
    container:
      image: salesforce/salesforcedx:latest-full
    steps:
      - name: Branch Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0
      - name: Authenticate QA Org
        run: |
          echo ${{ secrets.AUTH_URL }} > authURL
          sfdx auth:sfdxurl:store -f authURL -a "QA Org"
      - name: Generate Deployment Package
        run: |
          sfdx force:source:convert -r "force-app" -d "deploy/src/"
      - name: Validate Deployment
        id: validation
        run: |
          sfdx force:source:deploy -p "deploy/src/" -c -u "QA Org" --verbose